### ISSUE TITLE
ttyAMC0 drops off

### ISSUE THREAD

**Issue by amAtgit** [crleblanc/hackPump#2] opened 2013-06-23 11:16 UTC
Hi Chris, great work thanks for sharing. I used your hackpump project in mk802 minipc and I wanted let you know it works well.
Only issue I have come across is some times the serial port ttyAMC0 drops off and have unplug and plug the usb it toy to make it work again. Please see the error message in the hack pump.log.
Have come across this issue ? Can you suggest any  fix or workaround so I don't have to physically unplug ir toy?

Thanks 
Amol

hackpump.log:
2013-06-23 17:26:04,715 Traceback (most recent call last):
  File "/home/miniand/projects/hackPump/hackpump/hack_pump.py", line 72, in main
    set_temp(conf.serial_device, conf.ir_code_file, temp_now)
  File "/home/miniand/projects/hackPump/hackpump/hack_pump.py", line 44, in set_temp
    with serial.Serial(deviceName) as serialDevice:
  File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 261, in **init**
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 278, in open
    raise SerialException("could not open port %s: %s" % (self._port, msg))
SerialException: could not open port /dev/ttyACM0: [Errno 5] Input/output error: '/dev/ttyACM0'

**Comment by crleblanc** [comment] 2013-06-24 07:09
Hi Amol,

I'm glad to see you've had some success with it.  I've also been dealing
with some of these issues myself.

One thing you should try is upgrading pyirtoy to the latest version. I put
a bug fix in for bug #1 that "seems" to fix the issue of losing the device
from the system (it goes into bootloader mode. Fixed it by putting the
device back in sampling mode after a transmit), roughly one month ago.
However I'm seeing other issues with the irtoy now.  It gets into a state
where it hangs on the first serial read until its disconnected and
reconnected.  It's hard to reproduce so could be very hard to fix.  I see
the same issue when using the official irtoy record/playback command line
tools.  I've ordered a replacement irtoy on the off chance that the
hardware is faulty.

There's a good chance that these are firmware bugs.  The python code is
very simple, its just reading and writing to the serial device.  I've tried
transmitting over 1000 codes in an attempt to identify where the problem
might be, but it worked fine.  It seems to have a problem after an idle
period.  This is why I've bought a second irtoy, to rule out a hardware
fault.

While I'm familiar with C code I don't have any experience with debugging
firmware so might leave it to the experts.  I read a thread (sorry don't
have the link) from someone who made the irtoy enter bootloader mode when
he wasn't using it. It seems like a possible workaround but unfortunately I
don't have any experience with that.

Good luck.  Maybe try asking on the irtoy forum if it still drops the
serial device after updating pyirtoy.  Hopefully you'll get a friendlier
response than I did ;-)

Cheers,
Chris

**Comment by crleblanc** [comment] 2015-05-31 10:18
This bug appears to be caused by the IR toy firmware as discussed in https://github.com/crleblanc/PyIrToy/issues/2.  Closing issue since it's not caused by this project but the underlying irtoy firmware.

**Closed as completed by crleblanc** 2015-05-31 10:18 UTC
